#!/usr/bin/env php
<?php

$command = "docker-compose run --rm composer ";

foreach ($argv as $arg) {
    $command .= $arg === "./dc" ? "" : $arg . " ";
}

if (str_contains("create-project", $command)) {
    $command .= " .";
}

shell_exec($command);